import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_firebase/auth_service.dart';
import 'package:flutter_firebase/home_screen.dart';
import 'package:flutter_firebase/login_screen.dart';
import 'package:flutter_firebase/firebase_options.dart'; // Ensure this is generated by user

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // NOTE: You must generate firebase_options.dart using 'flutterfire configure'
  // or manually add it to your lib folder.
  // For now, I'm assuming it exists or you will add it.
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    // Fallback if options are not found, asking user to configure
    print("Firebase initialization failed: $e");
    // Ensure you have firebase_options.dart
  }

  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Firebase Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blueAccent),
        useMaterial3: true,
      ),
      home: const AuthWrapper(),
    );
  }
}

class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    final authService = AuthService();

    return StreamBuilder(
      stream: authService.authStateChanges,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        } else if (snapshot.hasData) {
          return const HomeScreen();
        } else {
          return const LoginScreen();
        }
      },
    );
  }
}
